### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by esuvari** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1106]
When I try to train, I get OOM error.

Even when I decrease the batch size to 1, I receive this:
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 2.33 GiB already allocated; 1.89 MiB free; 2.35 GiB reserved in total by PyTorch)`

ironically batch size 2 gives "tried to allocate 10.00MiB" error. You'd think reducing the batch size to 1 would make it try to allocate a lower MiB but that's not the case.

(After writing this, I tried all batch size values. Here's how it responded to each one. This just doesn't make sense)
BS 1: 20 MiB
BS 2: 10 MiB
BS 3: 20 MiB
BS 4: 20 MiB
BS 5: 20 MiB
BS 6: 20 MiB
BS 7: 12 MiB
BS 8: 14 MiB
BS 9: 16 MiB
BS 10: 16 MiB
BS 11: 18 MiB
BS 12: 20 MiB

I have a GeForce GTX 1650 GPU with 4MB RAM. Isn't this just enough to make it work?

**Comment by mixern6** [comment]
With my GTX 1660 (6GB) I manage to get to size 10, but the best performance is if I set it to 3.
After each training attempt I have to restart the process in order to release the graphics memory. Sometimes it doesn't help as all the memory is fragmented, in use by other applications or "lost" by RVC and I have to restart the computer and make sure there are no other running applications which would use the memory. Chrome, Edge and other browsers use a lot of memory, probably it is better to keep as few open tabs as possible.
