### ISSUE TITLE
Runtime Disconnection

### ISSUE THREAD

**Issue by SunshineMocha** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1145]
Hi, i tried to search for this issue but im not 100% sure its the same or not. 

Since yesterday I am having troubles running the RVC. The problem being that the runtime disconnects almost randomly. Now, I have no idea what's happening as I always trained my models without issues, is that a Google Colab issue or a repo issue? Any workaround known? Because it just says "lol ok no" and disconnects everything (erasing all the work done).

Message being: Connect to a runtime to activate file browsing.

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/127298037/6f06e6d6-6e30-479c-95eb-fc6910043e3d)
 

So just you know

**Comment by tdkumon** [comment]
Got the same issue for 2 days. It just disconnects without any error message after a few minutes (seems to be random, i always manage to finish processing data, but when i click Feature extraction it disconnects at 60-70%. I just tried to wait a bit before clicking Feature extraction and then it disconnected almost immediately)
I also tried using Chrome instead of Firefox, didn't work. And using another Google Account also doesn't work.

**Comment by SunshineMocha** [comment]
> Got the same issue for 2 days. It just disconnects without any error message after a few minutes (seems to be random, i always manage to finish processing data, but when i click Feature extraction it disconnects at 60-70%. I just tried to wait a bit before clicking Feature extraction and then it disconnected almost immediately) I also tried using Chrome instead of Firefox, didn't work. And using another Google Account also doesn't work.

exactly what happens to me

**Comment by JRabun517** [comment]
Same here.

**Comment by abc123807** [comment]
Same error. I can train for about 20-30 epochs, then it disconnects. I'm assuming it's because of gradio being disfavored by Google. They did the same with with Automatic1111 for Stable Diffusion.

**Comment by little-brother** [comment]
Duplicated #1123
