### ISSUE TITLE
Code disallowed by Google in Colab

### ISSUE THREAD

**Issue by omensight** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1152]
I am getting this issue, is there any way to avoid this?
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/34387536/351ac0fd-c958-4bd9-b319-1899218f1d32)

**Comment by fumiama** [comment]
Probably no.

**Comment by mocci24** [comment]
upgrade to colab pro or use another colab

**Comment by RonFusaishi** [comment]
> upgrade to colab pro or use another colab

ok then, what's a good alternative?

**Comment by Bruno5430** [comment]
apparently colab is restricting the use of RVC-WebUI on free accounts, there isn't an official statement afaik
But the guys at stable diffusion webUI suffered from the same issue https://github.com/camenduru/stable-diffusion-webui-colab/issues/405

> ok then, what's a good alternative?

You'll have to obfuscate any mention of the strings `Retrieval-based-Voice-Conversion-WebUI` and `VoiceConversionWebUI` (case sensitive) from your colab, otherwise you will still get disconnected without colab pro
![2023-09-03_21-59](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/111712756/650f634b-90b0-4e9b-8c52-f44345e984aa)
Encoding the string to base64 no longer works, contrary to what is mentioned in https://github.com/camenduru/stable-diffusion-webui-colab/issues/405#issuecomment-1561207734 , as colab detects it too now
![2023-09-03_22-02](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/111712756/a061ffb9-e70d-48f0-869f-aee609fffede)

**Comment by sonphantrung** [comment]
@omensight @RonFusaishi You may try [this one.](https://colab.research.google.com/github/sonphantrung/Mangio-RVC-Tweaks/blob/main/Retrieval_based_Voice_Conversion_WebUI_v2.ipynb)

**Comment by RonFusaishi** [comment]
> @omensight @RonFusaishi You may try [this one.](https://colab.research.google.com/github/sonphantrung/Mangio-RVC-Tweaks/blob/main/Retrieval_based_Voice_Conversion_WebUI_v2.ipynb)

nope, still disallowed
