### ISSUE TITLE
Bug with audio slicing

### ISSUE THREAD

**Issue by matthew99a** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1346]
Sometimes in the inference output, I can hear random clicks. It turns out that the slicing algorithm in the inference algorithm has a simple bug.

From my understanding, the algorithm tries to slice the audio by taking the most silent point inside an interval of audio

/main/infer/modules/vc/pipeline.py:

line 318 to 333
```        
        audio = signal.filtfilt(bh, ah, audio)
        audio_pad = np.pad(audio, (self.window // 2, self.window // 2), mode="reflect")
        opt_ts = []
        if audio_pad.shape[0] > self.t_max:
            audio_sum = np.zeros_like(audio)
            for i in range(self.window):
                audio_sum += audio_pad[i : i - self.window]
            for t in range(self.t_center, audio.shape[0], self.t_center):
                opt_ts.append(
                    t
                    - self.t_query
                    + np.where(
                        np.abs(audio_sum[t - self.t_query : t + self.t_query])
                        == np.abs(audio_sum[t - self.t_query : t + self.t_query]).min()
                    )[0][0]
                )
```

However, since audio_pad is a waveform with values both positive and negative, the sum of an interval of these values is not a good indication of the loudness at each point of the audio, which results in slicing in unexpected places. One solution could be to use the sum of audio_pad ** 2 instead.

**Comment by Afredi123** [comment]
You won't believe it, but this YouTube channel is making $10,000 per month easily because it has got more than 4 million views.
In the last 30 days, the channel has uploaded only 70 videos and it has gained almost 100,000 subscribers in just four months.
Moreover, all their videos have thousands of views.
All they do is upload simple videos and all their videos are created using a I.

**Comment by Afredi123** [comment]
You won't believe it, but this YouTube channel is making $10,000 per month easily because it has got more than 4 million views.
In the last 30 days, the channel has uploaded only 70 videos and it has gained almost 100,000 subscribers in just four months.
Moreover, all their videos have thousands of views.
All they do is upload simple videos and all their videos are created using a I.

**Comment by RVC-Boss** [comment]
Good idea! Do **2 or do abs for audio_pad first.

**Comment by RVC-Boss** [comment]
Fixed now.https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/dev/infer/modules/vc/pipeline.py#L324

**Comment by matthew99a** [comment]
Nice! Thanks for the fix!
