### ISSUE TITLE
[Question] WHat's the secret sauce behind the inference speed of RVC 10?

### ISSUE THREAD

**Issue by LuluViBritannia** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1434]
Hello! First of all, this isn't an issue, I'm just asking for information, I didn't know where else to ask this. Sorry if it's not the right place ^^'.

I updated to RVC 10.6, and noticed the incredibly fast inference! It went from a 1:1 ratio (1 minute of inference time for a 1 minute file) to a mind-blowing 240:1 (10 seconds inference for a 4 minutes file!!!).
You did an EXCELLENT job guys, I didn't expect to have such performance so soon!

Now, my question is... what did you do exactly for it to become so fast? And, more importantly, **could this secret sauce be applied to LLMs and Stable Diffusion?** Do you think you could share your experience with the communities working on AI text generators and AI image generators? I am now convinced that all current AI tech is far from optimized, and I can't wait for all fields to get the same quality/inference time ratio you guys pulled off!

**Comment by yxlllc** [comment]
First of all, 10 seconds inference for a 4 minutes file is 24:1...

Then, I think it may be that your infering speed was abnormal before. In fact, RVC's infering speed **should have been** that fast. For example, it may be that your RVC did not make full use of gpu acceleration due to software configuration issues. 

In addition, the choice of pitch extractor also affects the inference speed. If you use rmvpe, the speed is indeed very fast, but if you choose crepe or harvest, it will be very slow. I remember that the 0813 package already supports rmvpe. I wonder if you were using an older RVC version before.
