### ISSUE TITLE
AMD Linux running gui error

### ISSUE THREAD

**Issue by deadp** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1481]
VC1006AMD_Intel python3.8 gui_v1.py
/home/user/Downloads/RVC/RVC1006AMD_Intel/my_env/lib/python3.8/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
2023-10-28 20:51:33.542783: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-28 20:51:35 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-10-28 20:51:35 | INFO | faiss.loader | Successfully loaded faiss with AVX2 support.
2023-10-28 20:51:36 | INFO | configs.config | Found GPU AMD Radeon RX 6700 XT
is_half:True, device:cuda:0
Traceback (most recent call last):
  File "gui_v1.py", line 120, in load
    data = json.load(j)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui_v1.py", line 874, in <module>
    gui = GUI()
  File "gui_v1.py", line 114, in __init__
    self.launcher()
  File "gui_v1.py", line 153, in launcher
    data = self.load()
  File "gui_v1.py", line 134, in load
    "sg_input_device": input_devices[sd.default.device[0]],
IndexError: list index out of range

**Comment by suspecting** [comment]
Ditto, but using cpu. Everything in my requirements, etc. are installed

**Comment by ykk648** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/f431f8fb3f13aa6dfedf33383f70de35fe07dfbd/gui_v1.py#L125

sounddevice fail to get deafult device, so set the index to 0:

```
if data["sg_input_device"] not in input_devices:
    data["sg_input_device"] = input_devices[0]
if data["sg_output_device"] not in output_devices:
    data["sg_output_device"] = output_devices[0]
```

**Comment by deadp** [comment]
@ykk648 sorry are you recommending to replace this section of the code?

**Comment by ykk648** [comment]
@deadp check your `configs/config.json` file , it's blank or not, it may be corrupted

**Comment by deadp** [comment]
It is blank, what should I do?

**Comment by ykk648** [comment]
recover it https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/configs/config.json

**Comment by deadp** [comment]
This got it to launch, running into a new error now though. Thank you

**Comment by marischou** [comment]
To anyone still having problems with this, from
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/ff093ad88f01428e822c04ad64518fda85699614/gui_v1.py#L125-L128
I tried doing this
```python
                    if data["sg_input_device"] not in input_devices:
                        data["sg_input_device"] = input_devices[-1]
                    if data["sg_output_device"] not in output_devices:
                        data["sg_output_device"] = output_devices[-1]
```
which worked for me.

---
By printing testing sounddevice's `query_devices()` and `input_devices`, `output_devices` array, for my system (Linux Mint 21.2), I found out that the sounddevice's devices combined both the inputs and outputs together, while the `self.get_device()` on line 117 returned the correctly separated inputs and outputs. This caused me to get the `index out of range error`. For my system, in both `input_device` and `output_device` the default device sits on the last index, hence setting it to index [-1] worked for me.

To add, the config.json file being empty happens because, firstly, the first config.json reads and the list index error occurs, the try block goes to config write mode, and also meets the index error. The write fails, the config.json is corrupted.
