### ISSUE TITLE
How to turn off Normalization in the preprocessing script?

### ISSUE THREAD

**Issue by tylertraining** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1680]
Hi RVC Team,

I was wondering how someone could turn off RVC's
audio normalization in the pre-processing stage, so that only the normalization that was done separately by the user would be applied to the final audio files and so that RVC wouldn't apply normalization on the files again afterwards.

-----

嗨，RVC 团队、

我想知道如何在预处理阶段关闭 RVC 的
音频归一化，这样只有用户单独进行的归一化才会应用到最终音频文件，而且 RVC 之后不会再对文件应用归一化。

**Comment by ms903x1** [comment]
If you have manually processed the dataset, you can directly click on the feature extraction option in the web tab

**Comment by tylertraining** [comment]
> If you have manually processed the dataset, you can directly click on the feature extraction option in the web tab

Thank you for the reply and helpful answer, do you know if it's possible to apply only part of the preprocessing? Like everything, but normalization? I know that it slices the audio apart and seems to make a "0_gt" and "16k" folder, but I'm not sure if there are certain things I should do before skipping this step entirely directly to feature extraction. My datasets are cleaned of silences and noise with some dc offset mitigation + de-phasing + slight compression all done to one long file usually and also normalized to -3dB or -5dB.

**Comment by epietrocola** [comment]
Sorry to jump in with a question, can I ask you why you would want to avoid preprocessing normalization? Normalization by itself is not a destructive operation and I wouldn't mind leaving it happen on an already normalized sample. Asking because I am curious, maybe there's a reason I did not think of

**Comment by JoaCHIP** [comment]
I think I can explain that: Normalization is usually done by scanning through the audio and finding the loudest peak, then rasing the volume so that the peak hits exactly the maximum level possible.

There's a drawback: Imagine you have two .wav files of a person talking, recorded at the same level. One of the recordings also contains a the sound of the person accidentally dropping his keys on the floor. The sound of the keys will probably already be at maximum loudness, probably even clipped, so this .wav file will not change its volume when you normalize it. The other .wav file will be normalized, because there's no loud sound of keys dropping. **Result:** The two .wav files are no longer the same level, and RVC will treat them differently.

I think it should be possible to disable normalization.

**Comment by tylertraining** [comment]
> I think I can explain that: Normalization is usually done by scanning through the audio and finding the loudest peak, then rasing the volume so that the peak hits exactly the maximum level possible.
> 
> There's a drawback: Imagine you have two .wav files of a person talking, recorded at the same level. One of the recordings also contains a the sound of the person accidentally dropping his keys on the floor. The sound of the keys will probably already be at maximum loudness, probably even clipped, so this .wav file will not change its volume when you normalize it. The other .wav file will be normalized, because there's no loud sound of keys dropping. **Result:** The two .wav files are no longer the same level, and RVC will treat them differently.
> 
> I think it should be possible to disable normalization.

Indeed. It would be really useful.
