### ISSUE TITLE
No "dotenv" thing.

### ISSUE THREAD

**Issue by timakimit** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1871]
Error:
<"path"\RVC1006Nvidia>python infer-web.py
Traceback (most recent call last):
  File ""path"\RVC1006Nvidia\infer-web.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by fabyday** [comment]
did you install python-dot or requirements.txt?

**Comment by SeranaZ** [comment]
I have them all installed and its still is throwing a fit saying I don't have the module installed. Actually infuriating

**Comment by fabyday** [comment]
@SeranaZ  
that's weired. I mean did you activate your environment correctly?(aka conda venv whatever) I use vscode. vscode sometimes use default environment if you didn't specify environment. then It can't find specific module what you installed.

**Comment by SeranaZ** [comment]
I feel like its not recognizing 3.12 of python. Thats where dotenv is

**Comment by fabyday** [comment]
@SeranaZ 
strongly agree with you. how about checing the python path is correct?

'''which python'''
and then find dot-env in libray/site-package

**Comment by SeranaZ** [comment]
Im not sure how. Tips on linux syntax for the command to check?

**Comment by fabyday** [comment]
oh, I'm sorry I use cygwin or wsl. so I can use command mixed.

**Comment by SeranaZ** [comment]
It's activated, I checked. i got it to recognize 3.12. The issue: I can only run it on linux, not from go-web application AND it thinks I don't have the package i18n. This is the buggiest release I have ever seen, and 3.12 also has its fair shar of bugs, but a downgrade didn't get different results

**Comment by fabyday** [comment]
@SeranaZ 
could you show me your entire error message?

**Comment by SeranaZ** [comment]
I have all packages installed, I already checked. But I will send over the screenshots
![Screenshot 2024-03-16 134057](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/112958860/18842849-329e-46ee-8774-9bd0c8521dfc)
![Screenshot 2024-03-16 133815](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/112958860/c9981913-f8a4-44c4-9afb-6b0d6ea7d176)
heres when I run on linux versus batch file. I am mor successful on linux, I have the package from the first screenshot. it is only when I remove it trying to call it as a package that it functions but because unix has no GUI it never opens it, which is on me. However, running batch would open on previouu RVC updates so idk what the issue is with this update specifically

here is how it runs when I remove .i18n
![Screenshot 2024-03-16 134245](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/112958860/9f339b90-b3b2-4963-8d1b-254d09c3e1b6)
runs completely fine, there may be a bug outside of using python engine that they need to fix

**Comment by SeranaZ** [comment]
I was able to get a virtual environement going without heavy code modification, the only issue now is still no gui will open. I had to modify run because i could not find .venv because my actiavte syntax was no .venv, another coding issue they might need to fix

**Comment by fabyday** [comment]
@SeranaZ 
nice description. thanks. 


ok... i18n is existed on this project. you might know that.

I think it was caused by some reason. 

if project doesn't consider i18n as module, what about add __init__.py to i18n folder.

just add empty __init__.py. 

like this. 
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/28583613/15b08f44-9d9d-429d-82c3-a8b88c8596a9)

I commented like here for detail. 
https://docs.python.org/3/tutorial/modules.html

I think that i18n recognition is tiny problem.

**Comment by SeranaZ** [comment]
Deleting the .i18n causes no issues. I got everything working just fine
now. Calling .i18n is redundant because since it is already in RVC there is
no point in some instances. Vocal separation is clear, training is good,
GPU detected and it tells me that i18n is there and working whenever I
start it up. I got it to work through tinkering with the code, downgrading
to version 1.23 of numpy (python is dumb and decided to get rid of np.float
and just make it float, causing several issues with librosa) and using a
combo of linux and windows. The fact I had to jump through so many hoops
just to get this working is crazy, mostly because python cant decide what
it wants to do with its updates. Its not necessarily an RVC issue, besides
the fact that it favors windows set up which is an issue in more ways than
one when you dont account for debugging for linux (not sure about mac,
since I dont use it but seeing as they get their own shell files I'd guess
its dumb dumb proof)
All in all, a terrible experience. I cant explain why what I did works, it
just does. The life of a programmer in a nut shell. So note to anyone
having issues-if it throws i18n.i18n does not exist, try getting rid of the
second i18n and make sure you do NOT use anything about python 3.10 unless
you want to deal with numpy, getting yelled at about pytorch
incompatibility, and overall bash file hell.
I spent so much time on this I legit am confident I am qualified to help
trouble shoot rvc, thats how much time I have spent on this project
dubugging and understanding how to use it across multiple platforms. I
fixed or diagnosed several issues on my own, it was insane. It was like IT
role play how intense these issues absorbed my life.

Anyway, rant over. Its working, and I'm happy. May the next update not shit
the bed

**Comment by fabyday** [comment]
hahah. you were so mad. It is usally happended on this field. 
But I think you finally found your own solution. 

yes. I thought too.🤭

**Comment by danielraban** [comment]
What was the solve here? I am also facing this issue on mac

**Comment by SeranaZ** [comment]
Mac will have different issues so I can not help you

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved. dotenv is not imported now.
