### ISSUE TITLE
Improving Quality using more than 1000 epochs?

### ISSUE THREAD

**Issue by tomakorea** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#198]
Hi, I really love the work of all the contributors to this project, it's very exciting times ! I start to prefer to use your version over SVC Gui. However, I noticed that going from 5000 to 8800 epochs on SVC Gui training gives a noticeable higher quality in terms of audio. The voice is cleaner, it doesn't really help the pronounciation or the timbre of the voice, but I noticed it really helps on the final audio quality (less noise, sound is closer to the original WAV source). Would it be possible to make an "ultra" quality preset during training also on your software to match what Svc Gui offers? Thanks for all the wonderful work.

**Comment by THELASTOFUS** [comment]
It would be stupid to do this. there's diminishing returns and RVC is not SOVITS.

**Comment by tomakorea** [comment]
Ah I see, is there any way to improve the infer quality to make it closer to the original WAV files source used for training? I'm using studio quality voice WAVs, 12 minutes dataset separated in small 10seconds files. However, there is a significant amount of noise added to the final output even after train the model up to the maximum 1000 epochs.

**Comment by Tybost** [comment]
Most of my best voices are trained with 20-30 minutes of data. I've only trained a single voice with around 10 minutes and the result was lesser (more robotic / metallic sounds when breathing / speaking) but I do have voices that sound worse than trained ones with less data (so you have to figure out how much data a voice needs) some voices need more / some less.

On the training tab - there's a button to automatically splice audio into smaller files and I don't know if this matters or not... but it splits the audio files into 3-second lengths / wav / mono at 48kb. I personally split my audio files at 5 seconds each and have in the past tried larger one-minute audio files (gave a very bad result)

Make sure you're equipping the .NPY + .INDEX in [w-okada's](https://github.com/w-okada/voice-changer) voice changer since sometimes it does have a positive effect on audio quality (less roboticness)

Someone mentioned that training at maximum epoch is not always better for voices with less data (you could lose the identity of the original source speaker / introduce artifacts) but I haven't personally noticed this just yet.

**Comment by RVC-Boss** [comment]
Good trainset: more epochs may be better
Dirty trainset: default epoch (20) is ok. Don't write a very big number.

**Comment by trivikramak** [comment]
Any suggestion for the number of epochs for 3 hours of quality training data?

**Comment by LWSS** [comment]
> Is RVCv2 the current state-of-the-art open-source model for music?

yeah it's pretty good, I like beatricev2 as well
