### ISSUE TITLE
Please Release The "RVC 2.5" Experimental Models

### ISSUE THREAD

**Issue by MethanJess** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2197]
On Issue #2013. someone asked about RVCv3, and an RVC Developer said the following:
"We actually have some experimental models, but the performance improvements have not met expectations..."
![Screenshot 2024-07-16 112847](https://github.com/user-attachments/assets/066c4e77-1d5d-4654-a230-d3de1811c0a3)
While I understand that it has not met expectations, an improvement is still an improvement, and since RVCv3 is taking for absolute ever to release... why not just release these experimental models and call them "RVC 2.5" or something in the meantime..?

**Comment by yxlllc** [comment]
The improvement is indeed small, and the cost is to enlarge the model, and the training and inference speeds are much slower, so we think there is no point in releasing it. We are now studying training the contentvec encoder, which is expected to be the key to significantly improve performance

**Comment by MethanJess** [comment]
That makes sense, thanks for the response!

**Comment by codename0og** [comment]
> The improvement is indeed small, and the cost is to enlarge the model, and the training and inference speeds are much slower, so we think there is no point in releasing it. We are now studying training the contentvec encoder, which is expected to be the key to significantly improve performance

You see, there are people who care about quality and not speed. Speed means absolutely nothing when quality is underperforming and with that being said, all that " speed chasing " + relying on fp16 instead of just listening to Nadare when they mentioned bfloat16 usage is just foolish.
In reality, all it had to take was switch multiperioddiscriminator to something more sophisticated such as MSSBCQT or MSSTFT discriminators as I am currently experimenting with heavy rvc arch changes that are rather divergent from original rvc / applio.
Just wanted to say it, don't mind me ~
