### ISSUE TITLE
Code for Training from Scratch (Creating Base Model)

### ISSUE THREAD

**Issue by nonmetal** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#393]
Hello, 
first of all, thank you for all contributors which provide us amazing codes. 

I would like to ask that if there is a code that trains _**the model from scratch**_ without going through the pre-trained model. 
Currently, I am exploring the method of improved models of VITS to apply to the RVC model structure, and I am experiencing a problem that the parameters of the pre-trained model and the changed RVC model do not match. 

As it is mentioned in [issue 110](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/110) before, I was able to found traces of training-from-the-scratch with [`train_nsf_sim_cache_sid.py`](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/train/cmd.txt), but not in the repo. 

Could you please share the code for base model training? If you kindly share the method, I'm glad to share the methods by writing a guide for future developers.

Thank you.

**Comment by KushATrivedi** [comment]
> following this!
> 
> What I was planning to try was to start a training without loading the pre-trained models (I don't know if it will let me continue), and train a giant dataset of the particular language I am interested in.... If all goes well, I should be able to acquire the diction of that language in the speech conversions where the trained language comes into play.

@Mixomo did you try this approach? is the training successful without including pre-trained model?

**Comment by Mixomo** [comment]
> > following this!
> > 
> > What I was planning to try was to start a training without loading the pre-trained models (I don't know if it will let me continue), and train a giant dataset of the particular language I am interested in.... If all goes well, I should be able to acquire the diction of that language in the speech conversions where the trained language comes into play.
> 
> @Mixomo did you try this approach? is the training successful without including pre-trained model?

Sorry, I'm no longer involved with RVC. As I recall, training without a pre-trained model didn't yield results, as it requires a huge amount of audio, which is impossible for domestic GPU training. 
It's always best to have a pre-trained model on hand. A lot has changed in these past two years. The Applio project is where you should start. 
Their Discord server features detailed guides, base models, and more. They'll soon be integrating new vocoders that will improve audio quality. 
I have tried to do fine tuning from a base model, but the origin of the pronunciation problem lies in the feature extractors: Hubert and contentvec. While contentvec is an improvement on Hubert, it would require training a language-specific extractor, which no one has any clue how to do Because they are, let's say, completed projects and their training instructions are unfortunately not clear. 
Cheers.
