### ISSUE TITLE
how to use the F0 curve model？

### ISSUE THREAD

**Issue by HenryCheung898** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#477]
Does any one know what's the function of F0 curve file and how to use it?

**Comment by brunolm** [comment]
I don't know how to use it, but I think it's a replacement for `Transpose (integer, number of semitones, raise by an octave: 12, lower by an octave: -12):` where instead of changing the pitch for the entire song it changed based on timestamps on a file.

I could be wrong, but that's my best guess.

I don't know what this file looks like, would be nice to have an example somewhere.

**Comment by bulieme** [comment]
> I don't know how to use it, but I think it's a replacement for `Transpose (integer, number of semitones, raise by an octave: 12, lower by an octave: -12):` where instead of changing the pitch for the entire song it changed based on timestamps on a file.
> 
> I could be wrong, but that's my best guess.
> 
> I don't know what this file looks like, would be nice to have an example somewhere.

i think your explaination is kinda confusing, you see, he meant by the f0 pitch curve, not the transpose. you'll need a file to replace the extracted f0 (from harvest, crepe, parselmouth) to your SET f0 curve, the pitch curve is the f0. i've been using diff-svc a lot so i had knew about these things a lot.

i dont know how to make the f0 pitch curve, but i'll need someone tho

**Comment by Ap1075** [comment]
@HenryCheung898 how did you create the f0 pitch curve?
