### ISSUE TITLE
Python exited with an error

### ISSUE THREAD

**Issue by vladghs** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#485]
All goes well while installing, but right at the end when is should be launching i get hit with this error
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/135985464/d83c836d-dc04-4185-91e1-be6fb4a2f1e6)

**Comment by sethtallen** [comment]
The error indicates that the port RVC uses is already in use, which might mean you (or whatever this installer is) has already started an instance.
You can try to navigate to localhost:7865 and see if it returns anything. If it doesn't, restart your machine and open cmd and run `python C:\Users\Tiny\Documents\VOCAL AI\ai\Retrieval-based-Voice-Conversion-WebUI\infer-web.py`

**Comment by pawelrojek** [comment]
I had the same problem. It turned out to be "NTKDaemon.exe" running in the background using this port (that's from "Native Instruments"). Just putting it out here in case someone can't figure out what's going on. I guess if you're interested in RVC Project you might also be into music and have some NI app(s) installed.

To solve it I just permanently replaced 7865 with 7866 in configs\config.py. That's it. Works like a charm.

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved. The current behavior is to automatically find an available port for Gradio.
