### ISSUE TITLE
Possible to use API or script?

### ISSUE THREAD

**Issue by DaveScream** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#487]
I have trained models, need to inference .wav files with API

**Comment by sethtallen** [comment]
Check #299 where there are scripts written to run it via script. The one linked in the documentation is not working.

**Comment by sethtallen** [comment]
> hey guys- here's what i notice- when you use command line infer, it takes much longer than web gui. i assume that's because there' startup overhead associated with the process. i need a way to send files without that overhead for conversion. my idea is to send a post request to the server that the gui startup runs, but i don't know if that's possible. do you have any recommendations?

@njarecki 

What sort of speed differences are you talking here? How long does it take you with the command line infer, and how long does it take via GUI?

Also, how are you using the command line infer? I have mine running constantly as a 'worker', it waits for a file with conversion parameters, and processes based on those. Maybe you're introducing overhead by making it spin up then process your file.

But I'm curious to see what speed differences you're seeing. I actually see better somewhat performance via the script approach.

**Comment by njarecki** [comment]
Hi! Yes I think I’m experiencing the exact problem you say. It’s 15 seconds vs 4 for a conversion. How do you set yours up? Would love to do it the way you’re doing it!  --NicholasOn Jul 9, 2023, at 12:57 AM, Seth T. Allen ***@***.***> wrote:﻿

hey guys- here's what i notice- when you use command line infer, it takes much longer than web gui. i assume that's because there' startup overhead associated with the process. i need a way to send files without that overhead for conversion. my idea is to send a post request to the server that the gui startup runs, but i don't know if that's possible. do you have any recommendations?

@njarecki
What sort of speed differences are you talking here? How long does it take you with the command line infer, and how long does it take via GUI?
Also, how are you using the command line infer? I have mine running constantly as a 'worker', it waits for a file with conversion parameters, and processes based on those. Maybe you're introducing overhead by making it spin up then process your file.
But I'm curious to see what speed differences you're seeing. I actually see better somewhat performance via the script approach.

**Comment by sethtallen** [comment]
You can view my C4RD1N4L_V2 project on my page on how I'm using it, under the 'backend' folder. I run "process_discord.py" on startup.

**Comment by njarecki** [comment]
Seth very impressive can u hit me back on nick@creatormusic.net - yeah let's move offline. May have some work for you if you're interested

**Comment by Fizikaz** [comment]
Where are you hosting project? Do you have all the model files and CLI tool on the same server, or are you somehow splitting them? 
1. Would it be best to have Docker setup for API?
2. Or would it be best to just clone everything in the server and instead of running "python infer-web.py" run "python infer_cli.py [TRANSPOSE_VALUE] "[INPUT_PATH]" "[OUTPUT_PATH]" "[MODEL_PATH]" "[INDEX_FILE_PATH]" "[INFERENCE_DEVICE]" "[METHOD]" ?
3. Or should I use flask for API?

Any information on this would be very helpful!

**Comment by njarecki** [comment]
In the end we used the stock RVC distribution and used the existing gradio server api endpoints. Had to do a little python scripting to make it work with our setup but it does

**Comment by ChocoRicon** [comment]
Hello this was translated at DeepL, glad I found your threads.
I would also like to operate from the API or command line, which file should I play with in the recently uploaded RVC0813Nvidia?
Thank you.

**Comment by njarecki** [comment]
Google or ChatGPT “how to use gradio api endpoints “--NicholasOn Aug 19, 2023, at 7:04 PM, Rico ***@***.***> wrote:﻿
Hello this was translated at DeepL, glad I found your threads.
I would also like to operate from the API or command line, which file should I play with in the recently uploaded RVC0813Nvidia?
Thank you.

**Comment by sethtallen** [comment]
@Fizikaz
I've committed my updated CLI/API script to the main repo of RVC.
You have to to host the script on whatever you're hosting RVC on. It uses the same processes that RVC's UI uses.

@ChocoRicon 
If you wish to use my CLI tool, refer to infer_cli.py
If you want to use it in a script import infer_cli.py and call the vc_single function. If you wish to use it via CLI, there's an example usage in the script on how to call it. 
I have a project, C4RD1N4L_V2, if you want to see how I use it for example.

As for Gradio API.
You can try Gradio API endpoints. I have no clue how effective they are. But I've had good results with my API script. I think the API script gives you more control over what you're doing, personally.

**Comment by ChocoRicon** [comment]
Thanks, I can use it when I do as you say!
