### ISSUE TITLE
Training Cancel button and Model List Management 

### ISSUE THREAD

**Issue by jurassicjordan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#524]
The training needs a cancel or stop button to stop the training process, since training can easily be resumed, I see no reason why a simple stop button is too much. 

There also needs to be a way to manage the model list. Either on its own tab or just a button that opens a text doc to change the listed models

**Comment by RVC-Boss** [comment]
good idea

**Comment by Eipckz** [comment]
I +1 this as well ontop of the other one. Same thing, additionally, I would appreciate the inclusion of this feature in the standard build. I have a particular interest in periodically evaluating my voice models, approximately every 50 epochs. However, due to the excessive consumption of VRAM during training, my graphics card is unable to simultaneously handle both training and voice evaluation processes. Moreover, I have encountered difficulties restarting the training if I close the program. Therefore, I kindly request guidance on how to successfully restart the training process in such cases.

**Comment by jurassicjordan** [comment]
did you at least add the button?

**Comment by ImCloudmixer** [comment]
did you...

..... add the button?

**Comment by Eipckz** [comment]
why would you dig this up out of the grave... its been closed for 2 years.

**Comment by ImCloudmixer** [comment]
well was it added?
