### ISSUE TITLE
versions >=3.7,<3.11 are supported

### ISSUE THREAD

**Issue by Tylast** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#626]
I'm getting the below error regarding my version of Python.  I saw a closed issue where I thought this was fixed.  Any idea?

`  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_3/v2bjvfms3_vbz3m_4fpt_8_40000gn/T/pip-install-wzd9g6f0/numba_271ade5563ba445191f1ec8572097331/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/_3/v2bjvfms3_vbz3m_4fpt_8_40000gn/T/pip-install-wzd9g6f0/numba_271ade5563ba445191f1ec8572097331/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.4; only versions >=3.7,<3.11 are supported.
      [end of output]`

**Comment by TripleKiller666** [comment]
Simple, downgrade your Python to below <3.11
Then create a VENV (Virtual Environment) which will ensure that the Python Version IN THAT FOLDER, stays the same.
`python -m venv venv`
Then activate the VENV:
```
cd venv/scripts
activate
```
You should have (VENV) written in front of your Console now.
In this VENV Console you gonna install all your Python Components:
`pip install "WHATEVER PACKAGE YOU NEED HERE"`
Don´t forget to always activate the VENV again before you try to install or upgrade Python stuff, otherwise it will install the Components Systemwide, instead of only in the VENV.

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this version dependency issue has already been resolved.
