### ISSUE TITLE
Unable to train index

### ISSUE THREAD

**Issue by LuckyBlossom** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#665]
I think I’ve done everything correctly, but pressing train index does nothing. The last thing it shows in the output is an error message

/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 20 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Can I have some assistance please?

**Comment by LuckyBlossom** [comment]
I know like nothing about how this stuff works btw so if anybody’s gonna help I ask for something pretty easy to understand.

**Comment by Wisperer** [comment]
what python version are you using? I've found it's broken on 3.11

**Comment by marcomarao** [comment]
I have the exact same issue. Hope someone can sort that out for us. It just doesn't generate any index file, despite successfully making the pth. model correctly. I noticed though that there's been some issues previously... something related to loading the audio (fmpeg error) and also at the Pitch Extract it appears "no feature to do" instead of "all feature done". And of course there is the one you mentioned but that one doesnt appear to me everytime like the others.

**Comment by enokseth** [comment]
Same issue there, and training process continue in loop processing in web interface. 

![20230928_224401.jpg](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/84675089/2aec1d40-613a-4306-8372-8af3d7d2e0e4)

![20230928_224316.jpg](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/84675089/af2a9514-0d1b-474f-94ff-05f6f977ce9b)

![20230928_224301.jpg](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/84675089/17d2fa53-688a-42c6-b45a-a7668baba636)

**Comment by etale-cohomology** [comment]
I'm having the same issue with Python 3.10 on Ubuntu 22.04 with an RTX 4090.
