### ISSUE TITLE
Press any key to continue . . .

### ISSUE THREAD

**Issue by 40U538072** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#667]
C:\Users\Camer\Downloads\RVC-beta-v2-0618>runtime\python.exe -m pip install --upgrade tensorboard markdown
'runtime\python.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Camer\Downloads\RVC-beta-v2-0618>tensor-launch.py
Tensorboard can be accessed at: http://localhost:6006/

Active code page: 65001
working dir is C:\Users\Camer\Downloads\RVC-beta-v2-0618
downloading requirement aria2 check.

failed. please downloading aria2 from webpage!
unzip it and put in this directory!

Waiting for 5 seconds, press a key to continue ...

C:\Users\Camer\Downloads\RVC-beta-v2-0618>runtime\python.exe gui.py
'runtime\python.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Camer\Downloads\RVC-beta-v2-0618>pause
Press any key to continue . . .

C:\Users\Camer\Downloads\RVC-beta-v2-0618>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
'runtime\python.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Camer\Downloads\RVC-beta-v2-0618>pause
Press any key to continue . . .

Nothing will run at all no matter what I press or click, and it will not do anything at all. I already have all that I need to get it working.

**Comment by 40U538072** [comment]
@ath @scf4 @sungchura @hironow

**Comment by RVC-Boss** [comment]
If you want to use bat, you should download 7z package (the python runtime is contained) in huggingface.

**Comment by lintangtimur** [comment]
> If you want to use bat, you should download 7z package (the python runtime is contained) in huggingface.

i already download rvcv-beta.zip, and run go-web.bat and show error like above. Any solution?

**Comment by lintangtimur** [comment]
my solution is change
```
runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
pause
```
to
```
python infer-web.py --pycmd runtime\python.exe --port 7897
pause
```

**Comment by ravindars26** [comment]
जय श्री राम, Hello I'm not pro coding dude, but I love python and I solve this issue myself. 
here is the solution: I'm working on windows PC, which is C and Dot Net based language, if you have MAC, the same issue appears. Because "RVC Model" is based on different programing language: Which is _**PYTHON**_ .
So you have to _Tell your system: "Hey system please recognize this Python Language language"_  

**Go to YOUTUBE and search it:**
_**Windows User:**_ How To Install Python on windows 10 Set Python Path In Windows 10 | Set Path To Environment Variable: _ https://youtu.be/Z92vDtiVVYs?si=MP6-FYgb-QWmz7k5 _
_**MAC User:**_ How to Install Python on Mac OS and add to the PATH Variable |python tutorial | python for beginners: _ https://youtu.be/uZ6g1dM9oUk?si=tTqcQYWKtlmVZhbP _

Because RVC model interface is server based, and python help it to do so.
later I will upload example based video on YouTube and put link in comment section.

**Comment by BURNFIR3** [comment]
> my solution is change
> 
> ```
> runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
> pause
> ```
> 
> to
> 
> ```
> python infer-web.py --pycmd runtime\python.exe --port 7897
> pause
> ```

I do see the runtime\python.exe thing on the terminal, but how do i change it to what you sent here
