### ISSUE TITLE
[Question] What are the mute wavs used for?

### ISSUE THREAD

**Issue by Rolun** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#746]
Hi,

There are 2 mute wav files that get included in the training data.
2 questions:
1. If I train on multiple speakers, should I include 2 of these per speaker, or is just the set of 2 in total enough?
2. How do they benefit the model (conceptionally if nothing else)?

Many thanks in advance

**Comment by ms903x1** [comment]
Due to forced slicing, small datasets may lack silent segments after forced slicing, resulting in the model not being able to learn how to handle silent segments during inference. Silent segments during inference may generate noise. Adding additional mute waves to the training data is to address this issue.

**Comment by Rolun** [comment]
@ms903x1 - thanks!
So by the sounds of it, there doesn't need to be mute wav files for each speaker (or at all for longer datasets), just a couple in total in the dataset so the NSF-GAN can learn what silence is?

**Comment by RVC-Boss** [comment]
Yes.
