### ISSUE TITLE
I encountered noise while using real-time conversion

### ISSUE THREAD

**Issue by DokiYoloo** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#762]
**Thank you for this project, it's very useful.**

I followed all the instructions and completed all the steps without any surprise. Real time conversion is very effective in my ear and Windows recorder, but when I use voice messages in some chat software(like QQ), there may be some noise when it is sent out(And the sound is somewhat distorted). Therefore, I would like to know if this is caused by the audio sampling rate of the chat software or is it related to the sound quality when it is output. 

I can confirm that it is normal in the original microphone.

**Comment by masanbasa3k** [comment]
The audio sampling rate determines how many samples per second are captured or played back in a digital audio file. If there is a mismatch between the sampling rate used in the chat software and the sampling rate expected by the RVC model, it can result in noise or distortion during playback.

To troubleshoot this issue, you can try the following steps:

1. Check the audio settings in the chat software: Look for any options related to audio quality or sampling rate in the chat software's settings. Ensure that the sampling rate is set to a value compatible with the RVC model's requirements. If possible, try different sampling rate settings to see if it improves the output quality.

2. Verify the output settings: Check the output settings on your computer or in the chat software to ensure that the audio output device is correctly configured. Make sure that the device selected for output is the one you intend to use, and verify its settings, such as volume levels and any enhancements applied.

3. Test with different chat software: If possible, try using the RVC output with different chat software to see if the issue persists. This will help determine if the problem is specific to the chat software you mentioned or if it occurs across multiple platforms.

4. Consider audio format conversion: If the chat software supports different audio formats, you can try converting the output audio from the RVC model to a different format and see if it improves the quality when sent through the chat software.

It's also worth noting that the sound quality can be influenced by various factors, including the microphone used for recording. If the original microphone captures high-quality audio without noise or distortion, it suggests that the issue might be related to the chat software or the configuration settings.

I hope these suggestions help in troubleshooting the noise and distortion issue. Let me know if you need any further assistance.

**Comment by DokiYoloo** [comment]
> The audio sampling rate determines how many samples per second are captured or played back in a digital audio file. If there is a mismatch between the sampling rate used in the chat software and the sampling rate expected by the RVC model, it can result in noise or distortion during playback.
> 
> To troubleshoot this issue, you can try the following steps:
> 
> 1. Check the audio settings in the chat software: Look for any options related to audio quality or sampling rate in the chat software's settings. Ensure that the sampling rate is set to a value compatible with the RVC model's requirements. If possible, try different sampling rate settings to see if it improves the output quality.
> 2. Verify the output settings: Check the output settings on your computer or in the chat software to ensure that the audio output device is correctly configured. Make sure that the device selected for output is the one you intend to use, and verify its settings, such as volume levels and any enhancements applied.
> 3. Test with different chat software: If possible, try using the RVC output with different chat software to see if the issue persists. This will help determine if the problem is specific to the chat software you mentioned or if it occurs across multiple platforms.
> 4. Consider audio format conversion: If the chat software supports different audio formats, you can try converting the output audio from the RVC model to a different format and see if it improves the quality when sent through the chat software.
> 
> It's also worth noting that the sound quality can be influenced by various factors, including the microphone used for recording. If the original microphone captures high-quality audio without noise or distortion, it suggests that the issue might be related to the chat software or the configuration settings.
> 
> I hope these suggestions help in troubleshooting the noise and distortion issue. Let me know if you need any further assistance.

Thank you for your serious reply, it is very helpful to me! I will try the steps you said one by one.

I will close this issue
