### ISSUE TITLE
why this program not run at my mac

### ISSUE THREAD

**Issue by webstorm-dxy** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#815]

**Comment by Naozumi520** [comment]
Provide more details so I can help you. I didn't see any logs or errors

**Comment by bgomiss** [comment]
i also have Mac and there isn't enough tutorial here on how to install this on a m1 Mac for example

**Comment by Naozumi520** [comment]
Indeed there isn't enough tutorial. For now you can run `brew install ffmpeg` to install ffmpeg (You'll need to have brew install first), then run `sh ./run.sh` to install the dependency. It will also start RVC automatically.

**Comment by bgomiss** [comment]
on Mac m1 I get this error "rvc Unfortunately, there is no compatible GPU available to support your training." and I found this fix "pip install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu

export PYTORCH_ENABLE_MPS_FALLBACK=1" in here 

https://github.com/Tiger14n/RVC-GUI ( this guy is simpler than what we work on now?) how can I install this last one instead of the one we are currently on now?
