### ISSUE TITLE
Resume interrupted training work

### ISSUE THREAD

**Issue by k0xxxx** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#837]
Hello. Please tell me how can I resume training if I have a saved epoch file? I'm using free google colab and want to make sure I don't have enough 12 hour free session limit or another reasons

**Comment by fumiama** [comment]
You can backup logs/yourproject folder and restore it to original place at next training. Then fill exactly the same parameter but an increased epoch count.

**Comment by jayndjay** [comment]
Did you fixed it?

**Comment by snartin** [comment]
![Uploading 20240323_212300.jpg…]()

I trained my RVC voice model via Google Collab and due to the runtime error it got saved to just 200 Epochs. The next time I tried to resume the training, it showed me an saying:

SystemError: initialization of _pywrap_checkpoint_reader raised unreported exception

How do I fix it?
