### ISSUE TITLE
index search FAIL or disabled

### ISSUE THREAD

**Issue by JapanYoshi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#892]
Using go-realtime-gui.bat, voice conversion fails (no audio is output) and the command line intermittently repeats the error "index search FAIL or disabled".

**Comment by Quicksticks-oss** [comment]
I get the same error

**Comment by Qiu233** [comment]
same error since an unexpected restart due to CPU temperature too high.

**Comment by KenFlaut** [comment]
same error, too. What impact does this have? Will the output sound become worse?

**Comment by LeHungryBoi** [comment]
I got the same error and it works after switching the audio device to the MME one.

**Comment by ljw20180420** [comment]
This is because the logs folder does not contain kikiV1.index, keruanV1.index and guanguanV1.index is missing. These files are included in the old 7z file https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006Nvidia.7z. However, this 7z version has some bugs in using go-realtime-gui.bat. These bugs are fixed in #1994. Unfortunately, this patch has not been integrated into any 7z file.

In my case, I install RVC on windows by the following steps:
1. git clone git@github.com:RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git
2. download https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006Nvidia.7z and uncompress
3. copy the folders runtime, assets and logs from RVC1006Nvidia to Retrieval-based-Voice-Conversion-WebUI
4. runtime\python -m pip install FreeSimpleGUI (see #1978)
5. double click go-realtime-gui.bat
