### ISSUE TITLE
How do I continue training?

### ISSUE THREAD

**Issue by jassomsc** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#930]
I have saved the .tar.gz file, ran the first cell, opened the GUI, stopped the first cell, ran the second one while the load option and then in the train tab put the name of my model and click train, but it doesn't work. Tbh I'm absolutely confused at this point.

**Comment by NetIsPrograming** [comment]
Just put the same Name and Information (Version, Pitch Guidance, ETC) of your model under the train tab
and **DON'T** do pre-process or pitch extraction and it should start off from were it stopped.

**Comment by jassomsc** [comment]
> 

I get error, I don't know what am I doing wrong :(

**Comment by RVC-Boss** [comment]
.tar.gz is not the standard ckpt files format

**Comment by jassomsc** [comment]
Well that's the file I got when I ran the second cell, the one for saving a Google Drive Backup

> .tar.gz is not the standard ckpt files format

**Comment by jassomsc** [comment]
Closing without solving, nice 👍🏻

**Comment by cohan8999** [comment]
@jassomsc  - Finding your post while dealing with the same problem. Just wanted to say you didn't get any help because you didn't provide any information of your process, and expected the people here to automagically know what the specifics of your situation was. Also your general attitude and apparent neediness doesn't really do much to motivate people into helping you either.
