### ISSUE TITLE
Feature request: supporting safetensors

### ISSUE THREAD

**Issue by litagin02** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#960]
Recently, some of my trained pth files are marked as unsafe in hugging face.
For example, in below, some particular epochs are claimed to be unsafe and virus.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/139731664/4101ab6c-348c-4792-9bd6-32d7afa61c75)

It is obviously false virus warning, and I don't know why hugging face says that particular epochs are unsafe.
Although I know my models are safe, users may not want to download "unsafe" pth files (which use pickle, so I think it actually could be unsafe).
I think it's very nice if RVC could support safetensors format, not only pth files (maybe user can choose which one is used for trained output), for both training and inference (as in stable-diffusion-webui).
This will make everyone less worried about using (possibly dangerous) model files uploaded by others.

**Comment by WildBanjos** [comment]
Agree. Not long after stable diffusion (image generations) took off, there were a few scares in the community since pickle files were all that existed at the time. For anyone not aware, python pickle files can be very insecure, and it is possible to hide arbitrary code execution that runs when the file is loaded. Safetensors was developed to resolve this, allowing only the pure model to be shared without additional risk. 

Here[Here](https://huggingface.co/docs/safetensors/v0.3.2/index) is a link to the huggingface doc with the safetensors spec.

**Comment by rojii** [comment]
rvc gui is malware
